{
 "title": "Web traffic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Number of Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(http_requests_total[24h])) by (job)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(http_response_status{status=~\"[23]{1}[0-9]{2}\"}[24h])) by (job)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Failed Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(http_response_status{status=~\"[45]{1}[0-9]{2}\"}[24h])) by (job)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Number of Requests with Status 404 per Endpoint",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(last_over_time(http_requests_total_404[24h])) by (path)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Number of Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(http_unique_clients) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}